name: Build & Deploy Frontend

on:
  push:
    branches: ["main"]
    paths:
      - 'source/BudgetManager.UI/**' 
      - '.github/**'
env:
  AZURE_WEBAPP_NAME: hajs-manager
  AZURE_WEBAPP_PACKAGE_PATH: "source/BudgetManager.UI"
  AZURE_WEBAPP_PACKAGE_TARGET_DIRECTORY: "wwwroot"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install FE dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: npm install

      - name: Build FE
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: | 
          echo "${{ secrets.ENV_FILE }}" > .env.production
          npm run build -- -configuration --production --env-file .env.production
          cp -vr ./dist ./${{env.AZURE_WEBAPP_PACKAGE_TARGET_DIRECTORY}}

      - name: "Deploy"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_UI_PUBLISHPROFILE  }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{env.AZURE_WEBAPP_PACKAGE_TARGET_DIRECTORY}}"
