name: Build & Deploy API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: hajs
  AZURE_WEBAPP_PACKAGE_PATH: "source/BudgetManager.Api"
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build & Publish
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './myapp'
          cp -vr ./Assets ./myapp/Assets

      - name: Configure
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json
        env:
          AzureAd.Instance: ${{ secrets.AZURE_INSTANCE }}
          AzureAd.ClientId: ${{ secrets.AZURE_CLIENT_ID }}
          AzureAd.TenantId: ${{ secrets.AZURE_TENANT_ID }}
          AzureAd.Audience: api://${{ secrets.AZURE_CLIENT_ID }}
          ConnectionStrings.Database: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: "Deploy"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE  }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
